---
- name: slave
  hosts: slave
  tasks:
  - name: apt-update
    apt :
      update_cache: yes

  - name:  create directory
    file:
      path: "{{ item }}"
      state: directory
      mode: '0777'
    loop:
    - /home/ubuntu/jenkins_home
    - /home/ubuntu/bin

  - name: install jdk
    apt:
      name: openjdk-8-jdk
  - name: copy agent
    copy:
      src: ./agent.jar
      dest: /home/ubuntu/bin/agent.jar

